// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXBTlXMjcDxIVob43k2i0keyO1xZUk_WQ',
    appId: '1:823012817830:web:9cb0f5a08a96d87ce52d67',
    messagingSenderId: '823012817830',
    projectId: 'blooddonation-11947',
    authDomain: 'blooddonation-11947.firebaseapp.com',
    storageBucket: 'blooddonation-11947.firebasestorage.app',
    measurementId: 'G-TB5LZV7E7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf2rDvTvrd0lRY6-itcelsv-LmpACXeYs',
    appId: '1:823012817830:android:165a64edd1003911e52d67',
    messagingSenderId: '823012817830',
    projectId: 'blooddonation-11947',
    storageBucket: 'blooddonation-11947.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4PSNSzwTHuO4BF7uJACvxpViBHbcvSCI',
    appId: '1:823012817830:ios:8cb8b903e6899952e52d67',
    messagingSenderId: '823012817830',
    projectId: 'blooddonation-11947',
    storageBucket: 'blooddonation-11947.firebasestorage.app',
    iosBundleId: 'com.example.blooddonationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4PSNSzwTHuO4BF7uJACvxpViBHbcvSCI',
    appId: '1:823012817830:ios:8cb8b903e6899952e52d67',
    messagingSenderId: '823012817830',
    projectId: 'blooddonation-11947',
    storageBucket: 'blooddonation-11947.firebasestorage.app',
    iosBundleId: 'com.example.blooddonationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXBTlXMjcDxIVob43k2i0keyO1xZUk_WQ',
    appId: '1:823012817830:web:1e1171b801053633e52d67',
    messagingSenderId: '823012817830',
    projectId: 'blooddonation-11947',
    authDomain: 'blooddonation-11947.firebaseapp.com',
    storageBucket: 'blooddonation-11947.firebasestorage.app',
    measurementId: 'G-E8LCXF1BY5',
  );
}
